### ISSUE TITLE
getting this warning : sprintf():

### ISSUE THREAD

**Issue by Sharifur** [thomasgriffin/TGM-Plugin-Activation#732] opened 2018-02-25 07:13 UTC
I am getting this warning Warning: sprintf(): Too few arguments when installing plugins through TGMPA script on WordPress 4.8. Is this a known warning with latest version of WordPress?

**Comment by jrfnl** [comment] 2018-02-25 12:13
Closing as duplicate of #669 which was fixed by PR #670. The fix will be in the next release of TGMPA.

**Closed as completed by jrfnl** 2018-02-25 12:13 UTC
Labels: Status: Duplicate
