### ISSUE TITLE
Fatal Error on PHP 8.2 (Tested on localhost with wamp)

### ISSUE THREAD

**Issue by rafamem** [thomasgriffin/TGM-Plugin-Activation#824] opened 2024-05-20 15:04 UTC
Hi! After activate two plugins from the theme...

`Fatal error: Uncaught ArgumentCountError: 3 arguments are required, 2 given in C:\wamp\www\mytheme\wp-admin\includes\class-bulk-upgrader-skin.php:162 Stack trace: #0 C:\wamp\www\mytheme\wp-admin\includes\class-bulk-upgrader-skin.php(162): sprintf('%1$s installed ...', 'MITIC Accessibi...') #1 C:\wamp\www\mytheme\wp-content\themes\mytheme\inc\plugins\class-tgm-plugin-activation.php(3553): Bulk_Upgrader_Skin->after('MITIC Accessibi...') #2 C:\wamp\www\mytheme\wp-admin\includes\class-wp-upgrader.php(921): TGMPA_Bulk_Installer_Skin->after() #3 C:\wamp\www\mytheme\wp-content\themes\mytheme\inc\plugins\class-tgm-plugin-activation.php(3173): WP_Upgrader->run(Array) #4 C:\wamp\www\mytheme\wp-content\themes\mytheme\inc\plugins\class-tgm-plugin-activation.php(3278): TGMPA_Bulk_Installer->run(Array) #5 C:\wamp\www\mytheme\wp-content\themes\mytheme\inc\plugins\class-tgm-plugin-activation.php(2892): TGMPA_Bulk_Installer->bulk_install(Array) #6 C:\wamp\www\mytheme\wp-content\themes\mytheme\inc\plugins\class-tgm-plugin-activation.php(658): TGMPA_List_Table->process_bulk_actions() #7 C:\wamp\www\mytheme\wp-includes\class-wp-hook.php(324): TGM_Plugin_Activation->install_plugins_page('') #8 C:\wamp\www\mytheme\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #9 C:\wamp\www\mytheme\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #10 C:\wamp\www\mytheme\wp-admin\admin.php(259): do_action('appearance_page...') #11 C:\wamp\www\mytheme\wp-admin\themes.php(10): require_once('C:\\wamp\\www\\mit...') #12 {main} thrown in C:\wamp\www\mytheme\wp-admin\includes\class-bulk-upgrader-skin.php on line 162`

require_once get_template_directory() . '/inc/plugins/class-tgm-plugin-activation.php';

/inc/plugins/[plugins folders here]

**Comment by jrfnl** [comment] 2024-05-20 16:26
Closing as duplicate of https://github.com/TGMPA/TGM-Plugin-Activation/issues/669 which was fixed by PR https://github.com/TGMPA/TGM-Plugin-Activation/pull/670.

**Closed as not planned by jrfnl** 2024-05-20 16:26 UTC
Labels: Status: Duplicate
