### ISSUE TITLE
Permission error on multisite setup when clicking 'Begin installing plugin' link

### ISSUE THREAD

**Issue by JohEngstrom** [thomasgriffin/TGM-Plugin-Activation#239] opened 2014-12-03 17:01 UTC
I've found one issue.

In a multisite setup I've set an official repository plugin as required. The notice comes up in the admin but when clicking on the Begin installing plugin link I'm presented with "You do not have sufficient permissions to access this page.".

I am the only admin user on this WordPress install.

The URL the link goes to is /wp-admin/network/themes.php?page=tgmpa-install-plugins

**Comment by jrfnl** [comment] 2015-01-13 05:08
Probably duplicate of issue #228

**Closed** 2015-01-23 10:43 UTC
Labels: Duplicate
