### ISSUE TITLE
Warning: sprintf(): Too few arguments in \wp-admin\includes\class-bulk-upgrader-skin.php on line 156

### ISSUE THREAD

**Issue by jemyka** [thomasgriffin/TGM-Plugin-Activation#812] opened 2022-02-02 09:26 UTC
Hello,

Please help I am getting this errors when installing the plugins included on Transpix - Logistics Warehouse WordPress Theme
Note: New WordPress installation (WP Version 5.9)

Attached is the error am getting and the error file number 156.[
![Install-Required-Plugins-—-WordPress](https://user-images.githubusercontent.com/4558519/152126642-0c69c9f5-42b3-4fa4-a450-62ddfb6914d4.jpg)
![class-bulk-upgrader-skin](https://user-images.githubusercontent.com/4558519/152126891-eea121ce-3703-485b-8639-b06f65a9f979.jpg)
](url)

**Comment by clemensmol** [comment] 2023-01-12 16:34
You could try running your website using a version lower than PHP 8. If the theme isn't compatible with PHP8 report it at the theme developer.

**Comment by tbajorek-tomedio** [comment] 2024-04-17 23:02
This is warning, not exception, so seems @jemyka uses PHP<8. In PHP8+ instead of reporting a warning, PHP throws an exception in the case when there are less parameters passed than expected.
I have similar issue with Kivicare Wordpress template. In my case I see they added old version of TGMPA plugin to theme. You can find it and try to replace by current version from this repository. It may work, but maybe your theme is incompatible with PHP8 in more places.
So I also would like to advice you to contact with author of your theme to tell about this issue. It's for sure not related to this repository, but to your theme.

**Comment by jrfnl** [comment] 2024-05-20 16:27
Closing as duplicate of https://github.com/TGMPA/TGM-Plugin-Activation/issues/669 which was fixed by PR https://github.com/TGMPA/TGM-Plugin-Activation/pull/670.

**Closed as not planned by jrfnl** 2024-05-20 16:27 UTC
Labels: Status: Duplicate
