### ISSUE TITLE
An error occurred while installing PLUGIN NAME: Install package not available..

### ISSUE THREAD

**Issue by ryanlabelle** [thomasgriffin/TGM-Plugin-Activation#335] opened 2015-04-24 18:51 UTC
This only happens when I choose The Bulk Action / Install. When I click 'install' under the plugin name (single install) it works well.

Using 2.4.1

To reproduce:
1) Store zipped bundled plugin in theme folder.
2) Try installing plugin via the bulk method (Install Plugins / Use Bulk Actions / Install )

Here are my settings:

    array(
    'name'               => 'Meta Box Tabs', // The plugin name.
    'slug'               => 'meta-box-tabs', // The plugin slug (typically the folder name).
    'source'             => get_stylesheet_directory() . '/plugins/meta-box-tabs.zip', // The plugin source.
    'required'           => true, // If false, the plugin is only 'recommended' instead of required.
    'version'            => '0.1.1', // E.g. 1.0.0. If set, the active plugin must be this version or higher.
    'force_activation'   => true, // If true, plugin is activated upon theme activation and cannot be deactivated until theme switch.
    'force_deactivation' => false, // If true, plugin is deactivated upon theme switch, useful for theme specific plugins.
    'external_url'       => '', // If set, overrides default API URL and points to an external URL.
    ),

**Comment by ryanlabelle** [comment] 2015-04-24 19:51
Seems to only be an issue with bundled items. Cheers.

**Comment by jrfnl** [comment] 2015-04-24 19:59
Closing as duplicate of #316 which has already been fixed in develop by #321

**Closed by jrfnl** 2015-04-24 19:59 UTC
Labels: duplicate

**Comment by ryanlabelle** [comment] 2015-04-24 21:10
Okay, thanks again.
