### ISSUE TITLE
Bulk updating not working

### ISSUE THREAD

**Issue by rubenbristian** [thomasgriffin/TGM-Plugin-Activation#295] opened 2015-04-21 09:23 UTC
Hi

There seems to be an issue in the 2.4.0 version when you're trying to do a bulk update. Here's what i get:

Fatal error: Class 'TGM_Bulk_Installer' not found in class-tgm-plugin-activation.php on line 1590

**Comment by Stephen-Cronin** [comment] 2015-04-21 12:01
I seem to be able to replicate that right back to the original 2.4.0 from 18 Mar 2014. It seems it's been broken for some time and not introduced in today's updates related to security. Hopefully someone else can confirm this...

**Comment by GaryJones** [comment] 2015-04-21 15:35
Duplicate of #185?

**Closed by GaryJones** 2015-04-21 15:35 UTC
