### ISSUE TITLE
Error when installing multiple plugins.

### ISSUE THREAD

**Issue by AlexandruDoda** [thomasgriffin/TGM-Plugin-Activation#275] opened 2015-03-04 16:38 UTC
Fatal error: Class 'TGM_Bulk_Installer' not found in /Users/Alexandru-Doda/Websites/WPS/wp-content/themes/theme-name/engine/classes/class-plugin-activation.php on line 1576

**Comment by GaryJones** [comment] 2015-03-04 20:55
Duplicate of #185?

**Closed by GaryJones** 2015-03-04 20:55 UTC
Labels: Duplicate
