### ISSUE TITLE
Fatal error: Call to undefined function TGM_Bulk_Installer_Skin() in class-tgm-plugin-activation.php on line 1784

### ISSUE THREAD

**Issue by atikrahman146** [thomasgriffin/TGM-Plugin-Activation#347] opened 2015-04-25 19:24 UTC
Selecting list of all plugins and give command to install shows this error. I've downloaded new file just now.

Fatal error: Call to undefined function TGM_Bulk_Installer_Skin() in C:\xampp\htdocs\bio\wp-content\themes\salem\inc\class-tgm-plugin-activation.php on line 1784

**Comment by jrfnl** [comment] 2015-04-25 22:07
Closing as duplicate of already solved issue #185.

**Closed by jrfnl** 2015-04-25 22:07 UTC
Labels: duplicate
