### ISSUE TITLE
TGMPA doesn't translate to pt_BR

### ISSUE THREAD

**Issue by maxviewup** [thomasgriffin/TGM-Plugin-Activation#703] opened 2017-10-05 14:58 UTC
There is an pt_BR (and pt_PT) translate file on the TGMPA, but it doesn't work on my themes.  All messages still are in english.

Path of the theme:
`/Applications/MAMP/htdocs/sites/artemobi/wp-content/themes/arte-mobiliaria/`
Path of the TGMPA translate files on the theme:
`inc/plugin-activation/languages`

Include of the TGMPA:
```
@include_once get_parent_theme_file_path( '/inc/plugin-activation/class-tgm-plugin-activation.php' );
```
on the file `inc/plugins.php`

**Comment by jrfnl** [comment] 2017-10-05 22:16
Closing as duplicate of #656, please continue the conversation there.

**Closed as completed by jrfnl** 2017-10-05 22:16 UTC
Labels: Status: Duplicate, Component: Localization
