### ISSUE TITLE
Warning: sprintf(): Too few arguments in \wp-admin\includes\class-bulk-upgrader-skin.php on line 154

### ISSUE THREAD

**Issue by DKudleichuk** [thomasgriffin/TGM-Plugin-Activation#686] opened 2017-08-18 13:22 UTC
Hello!

Is there any fix please? Wordpress 4.8.1, TGM 2.6.1

![2017-08-18_16-20-56](https://user-images.githubusercontent.com/12991525/29460612-46441d14-8431-11e7-8e00-1a602ad65b15.png)

**Comment by jrfnl** [comment] 2017-08-18 14:10
Closing as duplicate of #669 which was fixed by PR #670. The fix will be in the next release of TGMPA.

**Closed as completed by jrfnl** 2017-08-18 14:10 UTC
Labels: Status: Duplicate

**Comment by saleeeem** [comment] 2018-06-08 18:12
i'm not understanding

**Comment by Progressed36** [comment] 2018-06-11 09:38
It says its fixed in next release, but after almost a year there is no new release?

**Comment by Remzi1993** [comment] 2018-10-19 10:39
There's still no fix.

**Comment by viettamus** [comment] 2018-12-20 20:55
You can fix it by replacing code in the file: www/wp-admin/includes/class-bulk-upgrader-skin.php
Old code:

```
if ( $this->result && ! is_wp_error( $this->result ) ) {
	if ( ! $this->error ) {
		echo '<div class="updated js-update-details" data-update-details="progress-' . esc_attr( $this->upgrader->update_current ) . '">' .
			'<p>' . sprintf( $this->upgrader->strings['skin_update_successful'], $title ) .
			' <button type="button" class="hide-if-no-js button-link js-update-details-toggle" aria-expanded="false">' . __( 'Show details.' ) . '</button>' .
			'</p></div>';
	}

	echo '<script type="text/javascript">jQuery(\'.waiting-' . esc_js($this->upgrader->update_current) . '\').hide();</script>';
}
```

New code:

```
if ( $this->result && ! is_wp_error( $this->result ) ) {
	if ( ! $this->error )
		echo '<div class="updated"><p>' . sprintf($this->upgrader->strings['skin_update_successful'], $title, 'jQuery(\'#progress-' . esc_js($this->upgrader->update_current) . '\').toggle();jQuery(\'span\', this).toggle(); return false;') . '</p></div>';
	echo '<script type="text/javascript">jQuery(\'.waiting-' . esc_js($this->upgrader->update_current) . '\').hide();</script>';
}
```

**Comment by MrShabir** [comment] 2019-01-12 06:44
@viettamus Its not a solution, Modify WordPress Core files are not a best solution.

**Comment by CreativeDive** [comment] 2019-01-14 09:07
When will this fix be released in the new version?

**Comment by magicstickuk** [comment] 2020-09-09 10:57
Still no proper fix?

**Comment by andyg2** [comment] 2022-11-06 12:05
Still no fix in 6.1 😕
