### ISSUE TITLE
Not so much an bug, but request for better place for the menu item (plugin usage)

### ISSUE THREAD

**Issue by cmwwebfx** [thomasgriffin/TGM-Plugin-Activation#305] opened 2015-04-22 13:49 UTC
It seems that by having TGM have a sub menu under appearance it is geared more in favour for theme developers. However as a plugin developer, it is confusing for the end user to look in appearance for installing plugins or extensions for a plugin to expand the functionality.

Can I suggest that if this is going to be a universal script for both themes and plugins that it be placed in a neutral ground such as "Tools" menu.

Plugins are not a place you will expect to find to be installed under the appearance menu.

**Comment by jrfnl** [comment] 2015-04-22 14:52
This is already accommodated in the `develop` branch.
Duplicate of #65, #188, #221

**Closed by jrfnl** 2015-04-22 14:52 UTC
Labels: duplicate
