### ISSUE TITLE
TGM missing feature in version

### ISSUE THREAD

**Issue by nomansbeauty** [thomasgriffin/TGM-Plugin-Activation#365] opened 2015-04-28 01:16 UTC
Hi,

Please see issue here and tell us possible solution:
https://www.dropbox.com/s/r0wegvfxoltpk1q/tgm-issue.PNG?dl=0

Thank you

**Comment by jrfnl** [comment] 2015-04-28 05:22
Closing as duplicate of #192, #197

**Closed by jrfnl** 2015-04-28 05:22 UTC
Labels: duplicate
