### ISSUE TITLE
Improve "Plugins need to be updated" workflow for packaged plugins...

### ISSUE THREAD

**Issue by makedesign** [thomasgriffin/TGM-Plugin-Activation#197] opened 2014-05-20 21:18 UTC
Would it be possible to allow users the ability to update the packaged plugins, rather than just notifying them that their version is no longer current?

IE: If I am including a plugin ZIP file and the user is prompted to update it during a theme update, there is no quick way for them to do so, even though I am including the most up-to-date plugin version inside the theme. 

Back story: Right now I am including this plugin with all of my themes to make theme & plugin updates a little easier for users: https://wordpress.org/plugins/easy-theme-and-plugin-upgrades/

This makes it easy for users to update themes & plugins without having to go through the deactivate/delete re-upload/re-activate process (and it makes backup ZIP copies, which is rad)... but I feel like the "holy grail" would be to allow users to update the packaged plugins in a similar sort of process during the TGM nag (rather than trying to convince them to read the documentation on how to do it manually). 

Is this totally far fetched? Am I missing another easier way of doing this?

Oh, and I recognize that force-deleting a plugin (in order to update it) is a lot different than force-activating/de-activating it (and that doing so on a Multisite installation without properly prompting the user that it'll update it for the whole network isn't good)... but if there's a way to include this feature, or even to just somehow integrate the "backup & update" process, it'd be incredibly helpful! 

Thanks for considering it!

**Comment by KingYes** [comment] 2015-01-13 15:51
+1 for this feature to be official.

**Comment by mintbird** [comment] 2015-02-18 03:59
+1 This is a *must have* feature.

**Comment by drewhammond** [comment] 2015-04-15 03:51
Any action on this?

**Comment by liviucerchez** [comment] 2015-04-23 06:27
A must have feature indeed.

**Comment by pavot** [comment] 2015-04-25 18:19
@swiderski created version of the latest version of this plugin with update functionality that can be found here: https://github.com/duckzland/TGM-Plugin-Activation/tree/add_update_mode 

I did test on my install and works perfectly.

Some discussion on this feature here: https://github.com/duckzland/TGM-Plugin-Activation/issues/3#issuecomment-96179802

Looking forward to have it as part of the original repo. Than you@swiderski !

**Comment by jrfnl** [comment] 2015-04-25 18:40
I suggest @swiderski or @duckzland make a pull request, so the code can be incorporated.

**Comment by pavot** [comment] 2015-04-25 20:17
With current dev pace it's quite a challenge :tired_face:

**Comment by swiderski** [comment] 2015-04-25 21:21
I did pull request, however now we are one version behind. But if there will be need I can merge again with most current version, but tomorrow, as I go sleep now:-)

**Comment by GaryJones** [comment] 2015-04-28 07:17
Closing this as a duplicate of #192. Subscribe to that ticket for future updates.

**Closed by GaryJones** 2015-04-28 07:17 UTC
Labels: enhancement

**Comment by jrfnl** [comment] 2015-05-03 04:41
I'd like to invite everyone in this thread to test PR #381 / https://github.com/thomasgriffin/TGM-Plugin-Activation/tree/feature/192-add-updating-workflow which implements this.

Feedback very welcome. Please add your comments in the PR thread #381
