### ISSUE TITLE
TGMPA v2.6.0 link issue

### ISSUE THREAD

**Issue by cristianstan** [thomasgriffin/TGM-Plugin-Activation#596] opened 2016-05-25 07:53 UTC
I've updated the TGMPA class from v2.5.2 to v2.6.0. All good so far. 

I accessed the site to install and activate the plugins and seems to be a problem with the links. Check this screenshot: http://awesomescreenshot.com/0f55w9gja7

I managed to fix this by making some edits:

**Line #2696** -> For install
`$actions['install'] = __( 'Install %s', 'tgmpa' );`
should be:
`$actions['install'] = __( 'Install', 'tgmpa' );`

**Line #2701** -> For update
`$actions['update'] = __( 'Update %s', 'tgmpa' );`
should be:
`$actions['update'] = __( 'Update', 'tgmpa' );`

**Line #2707** -> For activate
`$actions['activate'] = __( 'Activate %s', 'tgmpa' );`
should be:
`$actions['activate'] = __( 'Activate', 'tgmpa' );`

With my changes the links are just fine without the urls beside the texts(Activate. Install, Update);

Please let me know if what I did its ok. If so, I think that you should also update the code on github.

Thank you

**Comment by jrfnl** [comment] 2016-05-25 08:10
Closing as duplicate of #587 which was fixed in v2.6.1 which was released a week ago. If you upgrade, all will be fine again ;-)

**Closed as completed by jrfnl** 2016-05-25 08:10 UTC
Labels: Status: Duplicate

**Comment by cristianstan** [comment] 2016-05-25 08:17
@jrfnl  Thank you. I understand the update was made a week ago but from the official site http://tgmpluginactivation.com/download/ the last version is the same v2.6.0 The update should be made there aswell :)

**Comment by jrfnl** [comment] 2016-05-25 08:48
Not sure where you're looking, but the site was updated last week as well and shows me v 2.6.1.
