### ISSUE TITLE
Is there any if conditional statement for if all plugins where activated?

### ISSUE THREAD

**Issue by Ansif** [thomasgriffin/TGM-Plugin-Activation#613] opened 2016-07-19 12:45 UTC
Hi,

I need if condition for, if all plugins where activated. I've added my own sub menu of Install Plugins. But, if all plugins are installed and activated this will root to WordPress error page like : 
**You do not have sufficient permissions to access this page.**

So, please anyone let me know the if condition for it. So, i'll disable my sub menu once all plugins are activated.

Also, please share if you've more than that conditions. Like : All Plugins Installed, No Plugins Installed and All plugins are in de-activate mode - like so...

Thanks! :)

**Comment by jrfnl** [comment] 2016-07-19 13:21
Closing as duplicate of #484 #385 and #550.

> TGM_Plugin_Activation::get_instance()->is_tgmpa_complete()

**Closed as completed** 2016-07-19 13:23 UTC
Labels: Status: Duplicate, Type: Question

**Comment by Ansif** [comment] 2016-07-19 13:29
Hi,

I've checked that issues list already! Still not get right path.

Here is my sub-menu : 

<pre>
// Sub Menu Array
  $my_sub_menu = array(
    __('Welcome', 'text_domain') => 'my_page',
    __('Install Demos', 'text_domain') => 'install_demos',
    __('Install Plugins', 'text_domain') => 'install_plugins',
    __('Theme Options', 'text_domain') => 'theme_options'
  );
</pre>

I just want to hide **Install Plugins** menu from it. How can i call it?

**Comment by jrfnl** [comment] 2016-07-19 13:49
I gave you the answer already and there are code examples available in the linked issues. If you'd read those you should have been able to answer your own question.
