### ISSUE TITLE
Remove Plugins on theme deactivation

### ISSUE THREAD

**Issue by ljubacanoa** [thomasgriffin/TGM-Plugin-Activation#776] opened 2019-04-17 21:43 UTC
Closed topics nobody read.

I'm looking to found the way how to accomplish plugins removal on theme deactivation and I can't agree with argument for lack of option exposed in closed topic:

- Argument about depending plugin is wrong, as here is about the plugins bundled with theme (in other words, developer will take care about the listed plugins and its dependencies).
- That is only the option and should be set by default to false. So, it certainly will not affect nobody who don't need it.

So, please be kind and add the option (word say itself - option mean, optional usage).

**Comment by jrfnl** [comment] 2019-04-17 21:59
Marking this as a duplicate of #233 

IMO, the chance for abuse of such an option is way too high, so no, I'm not keen to add this or to even consider a PR for this.

**Closed as completed** 2019-08-02 21:48 UTC
Labels: Status: Wontfix, Status: Duplicate
